### ISSUE TITLE
Issue about installation

### ISSUE THREAD

**Issue by ddliugit** [mrsp/serow#2]
I try to estimate CoM, CoP, linear momentum and its derivative, angular momentum and its derivative online. Would your software be possible to do that?

Another issue I try to install your software. I installed pinocchio library, but the error appears like following while installing serow?

```
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "pinocchio" with
  any of the following names:

    pinocchioConfig.cmake
    pinocchio-config.cmake

  Add the installation prefix of "pinocchio" to CMAKE_PREFIX_PATH or set
  "pinocchio_DIR" to a directory containing one of the above files.  If
  "pinocchio" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  serow/CMakeLists.txt:8 (find_package)


-- Could not find the required component 'pinocchio'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "pinocchio" with
  any of the following names:

    pinocchioConfig.cmake
    pinocchio-config.cmake

  Add the installation prefix of "pinocchio" to CMAKE_PREFIX_PATH or set
  "pinocchio_DIR" to a directory containing one of the above files.  If
  "pinocchio" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  serow/CMakeLists.txt:8 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/jack/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/jack/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
```

Can you help me solve it?

**Comment by mrsp** [comment]
Hello 

SERoW estimates the 3D CoM position, velocity (Linear momentum) in the world frame,  the 3D Base Position, Velocity, Orientation plus its acceleration/angular velocity in the world frame (you can derive the base angular momentum yourself from that), and the 3D COP position in the world frame.

The error you get is related to pinnochio installation since SEROW can't find a valid pinnochio cmake version in the ros opt directory. Did you install pinnochio by: 
sudo apt-get install ros-kinetic-pinocchio ?

**Comment by ddliugit** [comment]
yes, I did.

I also installed pinocchio from source, would that matter?

ros opt directory? Can you indicate the detail about this directory?

Do you need to build pinocchio from source for serow?

**Comment by mrsp** [comment]
Hello again

No you don't need to install pinocchio from source for serow to function. The ros pinocchio package suffices. 

A good idea would be to remove your pinocchio source install from your machine to avoid possible conflicts.

SERoW with the default ros kinetic pinocchio version has been confirmed to properly function in multiple machines and in real-time on-board to robots. 

I'll assume you have ubuntu 16.04 x64 and ros-kinetic. Have you manually installed a different version of Boost? 

Again this seems as a pinocchio-boost compatibility issue.

**Comment by ddliugit** [comment]
I will install it in a clean ubuntu environment. If there is any issue, I will let you know.

**Comment by mrsp** [comment]
Yes please try that and kindly let me know if anything is wrong so we can fix any possible compatibility issue.

Thanks

**Comment by ddliugit** [comment]
I tried to install your software in a clean new ubuntu environment. Same error happens. 

It doesn't work. Can you help me out?

**Comment by ddliugit** [comment]
Actually your CMakeLists cannot work out either. 

My environment is ubuntu 16.04 and kinetic version. 

Same boost problem happened I think.

**Comment by ddliugit** [comment]
If that's caused by boost version, can you tell me which version should I use?

I used the default version. No new boost version is installed.

**Comment by ddliugit** [comment]
Can you help check the procedure I am using:
After installing kinetic in a clean ubuntu environment, I do:

```
sudo apt-get install ros-kinetic-pinocchio

cd ~/catkin_ws/src

git clone https://github.com/mrsp/serow.git

cd ..

catkin_make -DCMAKE_BUILD_TYPE=Release
```

**Comment by mrsp** [comment]
Hello 

you are right it must be and error in pinochio ros package and the default ros kinetic boost version.

I've raised an issue in the pinocchio repository for you:

https://github.com/stack-of-tasks/pinocchio/issues/1056

If they don't respond in time I ll provide means to compile serow with pinocchio by source.
Just give it a couple of days

**Comment by ddliugit** [comment]
Thanks. 

The problems seem caused by ros-kinectic-pinocchio.

Is it possible to install the old version of ros-kinectic-pinocchio?

**Comment by mrsp** [comment]
Hello there is a "dirty fix" around it check the 

> https://github.com/stack-of-tasks/pinocchio/issues/1056


i will properly  update the repository (probably tomorrow)  to be functional again and will come inform you.

**Comment by ddliugit** [comment]
Thanks.
Look forward to your fix.

**Comment by mrsp** [comment]
Its fixed just pull the master branch!

Let me know if you need any more help
